{"version": 2, "width": 64, "height": 19, "timestamp": 1657104747, "env": {"SHELL": "/bin/bash", "TERM": "xterm-256color"}}
[0.06426, "o", "INFO: imwheel started (pid=28723)\r\n"]
[0.065963, "o", "\u001b]0;mdavy@mdavy-pc:~/Hexlet/python-project-lvl1\u0007"]
[0.066074, "o", "\u001b[?2004h[mdavy@mdavy-pc python-project-lvl1]$ "]
[5.662133, "o", "b"]
[5.934836, "o", "r"]
[6.334848, "o", "a"]
[6.653875, "o", "i"]
[6.901507, "o", "n"]
[7.446073, "o", "-"]
[7.82183, "o", "e"]
[8.117594, "o", "v"]
[8.309698, "o", "e"]
[8.621799, "o", "n"]
[9.677348, "o", "\r\n\u001b[?2004l\r"]
[9.691527, "o", "Welcome to the Brain Even Game!\r\nMay i have your name? "]
[11.941566, "o", "M"]
[12.13404, "o", "i"]
[12.29337, "o", "k"]
[13.07796, "o", "e"]
[13.784283, "o", "\r\n"]
[13.784358, "o", "Hello, Mike!\r\nAnswer \"yes\" if the number is even, otherwise answer \"no\".\r\n"]
[13.784395, "o", "Question: 78\r\nYour answer: "]
[21.034446, "o", "y"]
[21.374074, "o", "e"]
[21.758895, "o", "s"]
[22.869689, "o", "\r\n"]
[22.86979, "o", "Correct!\r\nQuestion: 92\r\nYour answer: "]
[24.751228, "o", "y"]
[24.957209, "o", "e"]
[25.184923, "o", "s"]
[25.863151, "o", "\r\n"]
[25.863194, "o", "Correct!\r\n"]
[25.863207, "o", "Question: 95\r\n"]
[25.863332, "o", "Your answer: "]
[27.301397, "o", "n"]
[27.558384, "o", "o"]
[28.326618, "o", "\r\n"]
[28.326763, "o", "Correct!\r\nCongratulations, Mike!\r\n"]
[28.329657, "o", "\u001b]0;mdavy@mdavy-pc:~/Hexlet/python-project-lvl1\u0007"]
[28.329727, "o", "\u001b[?2004h[mdavy@mdavy-pc python-project-lvl1]$ "]
[30.973861, "o", "brain-even"]
[32.968615, "o", "\r\n\u001b[?2004l\r"]
[32.983033, "o", "Welcome to the Brain Even Game!\r\nMay i have your name? "]
[36.497909, "o", "B"]
[36.837764, "o", "i"]
[37.070705, "o", "l"]
[37.205865, "o", "l"]
[38.245373, "o", "\r\n"]
[38.245484, "o", "Hello, Bill!\r\nAnswer \"yes\" if the number is even, otherwise answer \"no\".\r\nQuestion: 79\r\nYour answer: "]
[40.166536, "o", "y"]
[40.366768, "o", "e"]
[40.593326, "o", "s"]
[41.232586, "o", "\r\n"]
[41.232692, "o", "'yes' is wrong answer ;(. Correct answer was 'no'.\r\nLet's try again, Bill!\r\n"]
[41.235389, "o", "\u001b]0;mdavy@mdavy-pc:~/Hexlet/python-project-lvl1\u0007"]
[41.235411, "o", "\u001b[?2004h[mdavy@mdavy-pc python-project-lvl1]$ "]
[43.743078, "o", "brain-even"]
[44.086351, "o", "\r\n\u001b[?2004l\r"]
[44.100737, "o", "Welcome to the Brain Even Game!\r\n"]
[44.100862, "o", "May i have your name? "]
[45.155015, "o", "B"]
[45.541419, "o", "i"]
[45.833402, "o", "l"]
[45.965816, "o", "l"]
[47.303036, "o", "\r\n"]
[47.303076, "o", "Hello, Bill!\r\nAnswer \"yes\" if the number is even, otherwise answer \"no\".\r\n"]
[47.303206, "o", "Question: 41\r\nYour answer: "]
[49.833618, "o", "n"]
[50.653412, "o", "\r\n"]
[50.653512, "o", "'n' is wrong answer ;(. Correct answer was 'no'.\r\nLet's try again, Bill!\r\n"]
[50.656111, "o", "\u001b]0;mdavy@mdavy-pc:~/Hexlet/python-project-lvl1\u0007"]
[50.656138, "o", "\u001b[?2004h[mdavy@mdavy-pc python-project-lvl1]$ "]
[53.565722, "o", "e"]
[53.837995, "o", "x"]
[54.095475, "o", "i"]
[54.390282, "o", "t"]
[54.664606, "o", "\r\n\u001b[?2004l\r"]
[54.664734, "o", "exit\r\n"]
